"use strict";
const fs = require("fs");
const path = require("path");

const ROOT = __dirname;
const OUT = path.join(ROOT, "dist");

// src first (so OrgChart.render is defined regardless of vendor), vendor last.
const JS_FILES = [
  "src/dataAdapter.js", "src/layout.js", "src/render.js", "src/interactions.js",
  "src/search.js", "src/settings.js", "src/dom.js", "src/export.js", "src/app.js",
  "vendor/html-to-image.min.js"
];
const CSS_FILES = ["styles/themes.css", "styles/app.css", "styles/chart.css"];

const JS_BANNER =
"/*!\n" +
" * orgchart.js - bundled build. DO NOT EDIT.\n" +
" * Auto-generated by build.js from src/ + vendor/. Re-run: node build.js\n" +
" *\n" +
" * Usage:\n" +
" *   <div id=\"chart\" style=\"height:600px\"></div>\n" +
" *   <link rel=\"stylesheet\" href=\"orgchart.css\">\n" +
" *   <script src=\"orgchart.js\"></script>\n" +
" *   <script>\n" +
" *     var chart = OrgChart.render('chart', { data: rawItemsArray });\n" +
" *     // chart.update(newData); chart.fit(); chart.destroy();\n" +
" *   </script>\n" +
" */\n";

const CSS_BANNER =
"/*!\n" +
" * orgchart.css - bundled build. DO NOT EDIT.\n" +
" * Auto-generated by build.js from styles/. Re-run: node build.js\n" +
" */\n";

function concat(files) {
  return files.map(function (f) {
    return "/* ==== " + f + " ==== */\n" + fs.readFileSync(path.join(ROOT, f), "utf8");
  }).join("\n");
}

fs.mkdirSync(OUT, { recursive: true });
fs.writeFileSync(path.join(OUT, "orgchart.js"), JS_BANNER + "\n" + concat(JS_FILES) + "\n", "utf8");
fs.writeFileSync(path.join(OUT, "orgchart.css"), CSS_BANNER + "\n" + concat(CSS_FILES) + "\n", "utf8");
console.log("Built dist/orgchart.js and dist/orgchart.css");
